# Generated by Django 4.2.20 on 2026-07-16 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('name_sw', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
