# Generated by Django 4.2.20 on 2026-08-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeengine',
            name='office_image_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storeengine',
            name='office_image_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storeengine',
            name='office_image_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
