# Generated by Django 4.2.20 on 2026-08-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_storeengine_office_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsengine',
            name='category',
        ),
        migrations.AddField(
            model_name='productsengine',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_subcategory', to='products.subcategory'),
        ),
    ]
