# Generated by Django 4.2.20 on 2026-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productsengine_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['user'], name='products_en_user_id_e0a5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['store_id'], name='products_en_store_i_325acf_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['sub_category'], name='products_en_categor_268453_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['parent_category'], name='products_en_parent__7a6264_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['leaf_category'], name='products_en_leaf_ca_ef036e_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['brand_id'], name='products_en_brand_i_2fbed3_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_approved'], name='products_en_is_appr_ef79c4_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_featured'], name='products_en_is_feat_ec92f8_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_flash_sale'], name='products_en_is_flas_a00639_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_wholesale'], name='products_en_is_whol_d81a26_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_retail'], name='products_en_is_reta_bcc948_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['enable_sizes'], name='products_en_enable__abc761_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['has_colors'], name='products_en_has_col_4fc138_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['enable_pickup'], name='products_en_enable__0cdc11_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['-views'], name='products_en_views_9c6bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['-created_at'], name='products_en_created_8c1b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['price'], name='products_en_price_18314f_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['average_rating'], name='products_en_average_982e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['order_count'], name='products_en_order_c_97c40a_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['name'], name='products_en_name_659c41_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['sku'], name='products_en_sku_1dcf57_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['barcode'], name='products_en_barcode_7a602d_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_approved', '-views'], name='products_en_is_appr_c7c141_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_approved', '-created_at'], name='products_en_is_appr_25a637_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['store_id', 'is_approved'], name='products_en_store_i_7f1ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['leaf_category', 'is_approved'], name='products_en_leaf_ca_cefc74_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['sub_category', 'is_approved'], name='products_en_categor_c60748_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['parent_category', 'is_approved'], name='products_en_parent__2d47a0_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_featured', 'is_approved'], name='products_en_is_feat_f803cb_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_flash_sale', 'is_approved'], name='products_en_is_flas_ccb4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_wholesale', 'is_approved'], name='products_en_is_whol_750302_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_retail', 'is_approved'], name='products_en_is_reta_c0619a_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['store_id', 'leaf_category', 'is_approved'], name='products_en_store_i_91b9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['store_id', 'sub_category', 'is_approved'], name='products_en_store_i_8cd21c_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_approved', 'price'], name='products_en_is_appr_0c4b85_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_approved', '-average_rating'], name='products_en_is_appr_956017_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['is_approved', '-order_count'], name='products_en_is_appr_f5d5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='productsengine',
            index=models.Index(fields=['cover_image'], name='products_en_cover_i_1749fd_idx'),
        ),
    ]
