# Generated by Django 4.2.20 on 2026-07-16 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('store_id', models.UUIDField()),
                ('brand_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('compare_at_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('price_tiers', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('size_stock', models.JSONField(blank=True, default=dict)),
                ('available_sizes', models.JSONField(blank=True, default=list)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('target_audience', models.JSONField(blank=True, default=list)),
                ('is_wholesale', models.BooleanField(default=False)),
                ('is_retail', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('enable_sizes', models.BooleanField(default=True)),
                ('has_colors', models.BooleanField(default=False)),
                ('enable_pickup', models.BooleanField(default=False)),
                ('shipping_method', models.CharField(default='fixed', max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_rate_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_default_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_dar_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_outside_dar_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_remote_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_stock_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expected_total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_months', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('moq', models.IntegerField(default=1)),
                ('views', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('size_format', models.CharField(default='standard', max_length=50)),
                ('condition', models.CharField(default='new', max_length=50)),
                ('engine_index', models.IntegerField(default=0)),
                ('price_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_foot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('sale_end_date', models.DateTimeField(blank=True, null=True)),
                ('offer_started_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('fee_due_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('leaf_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_products', to='products.category')),
            ],
            options={
                'db_table': 'products_engines',
            },
        ),
    ]
