# Generated by Django 4.2.20 on 2026-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsengine_products_en_user_id_e0a5ac_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories_name_98d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name_sw'], name='categories_name_sw_e3dc21_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['icon_name'], name='categories_icon_na_34e314_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created_at'], name='categories_created_9211a1_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'name_sw'], name='categories_name_7a235e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['icon_name', 'name'], name='categories_icon_na_7b574a_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['sub_category'], name='leaf_catego_sub_cat_c6674b_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['name'], name='leaf_catego_name_06c22b_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['name_sw'], name='leaf_catego_name_sw_8aee8e_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['icon_name'], name='leaf_catego_icon_na_f760f6_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['meta_title'], name='leaf_catego_meta_ti_9781fe_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['meta_description'], name='leaf_catego_meta_de_8fcd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['require_gender'], name='leaf_catego_require_5f0af9_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['require_size'], name='leaf_catego_require_e0d12a_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['color_required'], name='leaf_catego_color_r_f033a6_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['warranty_required'], name='leaf_catego_warrant_c60a31_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['weight_required'], name='leaf_catego_weight__cc08a9_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['dimensions_required'], name='leaf_catego_dimensi_40e21f_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['bulk_pricing_tiers'], name='leaf_catego_bulk_pr_6b2c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['min_stock_warning'], name='leaf_catego_min_sto_f0d43e_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['measurement_unit'], name='leaf_catego_measure_9804d9_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['size_format'], name='leaf_catego_size_fo_2a3974_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['material_type'], name='leaf_catego_materia_e0423f_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['color_hex'], name='leaf_catego_color_h_94b0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['-created_at'], name='leaf_catego_created_d14f91_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['name', 'name_sw'], name='leaf_catego_name_d22232_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['sub_category', 'name'], name='leaf_catego_sub_cat_0c0707_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['sub_category', 'name_sw'], name='leaf_catego_sub_cat_b24b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['sub_category', 'require_gender'], name='leaf_catego_sub_cat_bf8ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['sub_category', 'require_size'], name='leaf_catego_sub_cat_03522c_idx'),
        ),
        migrations.AddIndex(
            model_name='leafcategory',
            index=models.Index(fields=['sub_category', 'color_required'], name='leaf_catego_sub_cat_438dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='sub_categor_categor_e70bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name'], name='sub_categor_name_a8bf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name_sw'], name='sub_categor_name_sw_a9bbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['-created_at'], name='sub_categor_created_6817c4_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name', 'name_sw'], name='sub_categor_name_deec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'name'], name='sub_categor_categor_0a2b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'name_sw'], name='sub_categor_categor_df4088_idx'),
        ),
    ]
