# Generated by Django 4.2.20 on 2026-07-16 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsengine'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('name_sw', models.CharField(blank=True, max_length=255, null=True)),
                ('require_gender', models.BooleanField(default=False)),
                ('require_size', models.BooleanField(default=False)),
                ('color_required', models.BooleanField(default=False)),
                ('warranty_required', models.BooleanField(default=False)),
                ('weight_required', models.BooleanField(default=False)),
                ('dimensions_required', models.BooleanField(default=False)),
                ('bulk_pricing_tiers', models.BooleanField(default=False)),
                ('min_stock_warning', models.IntegerField(default=5)),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('size_format', models.CharField(blank=True, max_length=50, null=True)),
                ('material_type', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('condition_options', models.JSONField(blank=True, default=list, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('specs', models.JSONField(blank=True, default=list, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_categories', to='products.subcategory')),
            ],
            options={
                'db_table': 'leaf_categories',
            },
        ),
    ]
