# Generated by Django 4.2.20 on 2026-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_categories_name_98d7d5_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['owner'], name='stores_engi_owner_i_c6fa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['category'], name='stores_engi_categor_7daafa_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['store_name'], name='stores_engi_store_n_3a2b45_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['store_slug'], name='stores_engi_store_s_30e590_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['phone_number'], name='stores_engi_phone_n_9a9df6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['email'], name='stores_engi_email_a468ed_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['city'], name='stores_engi_city_2cc504_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['physical_address'], name='stores_engi_physica_562c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['instagram_handle'], name='stores_engi_instagr_48dde5_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['whatsapp_number'], name='stores_engi_whatsap_2a5c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['twitter_handle'], name='stores_engi_twitter_0908a3_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['tiktok_handle'], name='stores_engi_tiktok__e6ba33_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['is_verified'], name='stores_engi_is_veri_ce6fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['is_active'], name='stores_engi_is_acti_5c03a5_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['status'], name='stores_engi_status_551ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['verification_status'], name='stores_engi_verific_6fac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['-created_at'], name='stores_engi_created_4c8054_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['-total_sales'], name='stores_engi_total_s_b57586_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['-average_rating'], name='stores_engi_average_73f17e_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['store_index'], name='stores_engi_store_i_4e92b3_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['business_type'], name='stores_engi_busines_a120e2_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['category', 'is_active'], name='stores_engi_categor_5df477_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['category', 'is_verified'], name='stores_engi_categor_9c187e_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['category', 'status'], name='stores_engi_categor_19ad3c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['is_active', 'is_verified'], name='stores_engi_is_acti_46c0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['is_active', 'verification_status'], name='stores_engi_is_acti_d23033_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['store_name', 'city'], name='stores_engi_store_n_fb67df_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['city', 'is_active'], name='stores_engi_city_664daf_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['category', '-average_rating'], name='stores_engi_categor_446e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='storeengine',
            index=models.Index(fields=['is_verified', '-average_rating'], name='stores_engi_is_veri_452fee_idx'),
        ),
    ]
