# Generated by Django 4.2.20 on 2026-07-16 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_profile_admin_productvariation_productmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=100, null=True)),
                ('moq', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('store_name', models.CharField(max_length=255)),
                ('store_slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('store_banner', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('store_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('specialist_tags', models.JSONField(blank=True, default=list)),
                ('youtube_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('office_images', models.JSONField(blank=True, default=list)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sub_category_ids', models.JSONField(blank=True, default=list)),
                ('store_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='products.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='products.profile')),
            ],
            options={
                'db_table': 'stores_engine',
            },
        ),
    ]
