# Generated by Django 4.2.20 on 2026-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_storeengine_stores_engi_owner_i_c6fa9c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['user'], name='advertiseme_user_id_cf8b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['store_id'], name='advertiseme_store_i_a9e1be_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['approved_by'], name='advertiseme_approve_59add8_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['rejected_by'], name='advertiseme_rejecte_82e0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['business_name'], name='advertiseme_busines_68b5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['ad_type'], name='advertiseme_ad_type_a82d67_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status'], name='advertiseme_status_1b1a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['media_type'], name='advertiseme_media_t_add222_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-created_at'], name='advertiseme_created_4b312b_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-approved_at'], name='advertiseme_approve_001157_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['store_id', 'status'], name='advertiseme_store_i_10c24f_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['store_id', 'ad_type'], name='advertiseme_store_i_3b5600_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', '-created_at'], name='advertiseme_status_581677_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'ad_type'], name='advertiseme_status_efada0_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['store_id', 'status', '-created_at'], name='advertiseme_store_i_d705ab_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['user', 'status'], name='advertiseme_user_id_38ee86_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'media_type'], name='advertiseme_status_45d396_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['approved_by', 'status'], name='advertiseme_approve_a190bc_idx'),
        ),
    ]
