# Generated by Django 4.2.20 on 2026-08-08 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_advertisement_advertiseme_user_id_cf8b3d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_codes',
                'indexes': [models.Index(fields=['email'], name='otp_codes_email_b20ef6_idx'), models.Index(fields=['otp'], name='otp_codes_otp_542e45_idx'), models.Index(fields=['email', 'otp'], name='otp_codes_email_eece01_idx'), models.Index(fields=['created_at'], name='otp_codes_created_4cefc5_idx'), models.Index(fields=['is_used'], name='otp_codes_is_used_51d459_idx'), models.Index(fields=['email', 'is_used'], name='otp_codes_email_87b768_idx')],
            },
        ),
    ]
