# Generated by Django 4.2.20 on 2026-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
