# Generated by Django 4.2.20 on 2026-08-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_profile_is_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsengine',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
