# Generated by Django 4.2.20 on 2026-07-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeengine',
            name='tin_image_url',
        ),
        migrations.AddField(
            model_name='storeengine',
            name='tin_image',
            field=models.ImageField(blank=True, null=True, upload_to='tin_verification/'),
        ),
        migrations.AlterField(
            model_name='storeengine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storeengine',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
        migrations.AlterField(
            model_name='storeengine',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
