# Generated by Django 4.2.20 on 2026-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_storeengine_tin_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeengine',
            name='office_images',
        ),
        migrations.AddField(
            model_name='storeengine',
            name='office_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='store_offices/'),
        ),
        migrations.AddField(
            model_name='storeengine',
            name='office_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='store_offices/'),
        ),
        migrations.AddField(
            model_name='storeengine',
            name='office_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='store_offices/'),
        ),
    ]
