# Generated by Django 4.2.20 on 2026-08-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
