# Generated by Django 4.2.20 on 2026-07-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_storeengine_office_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeengine',
            name='store_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
