# Generated by Django 4.2.20 on 2026-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_storeengine_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsengine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_covers/'),
        ),
        migrations.AlterField(
            model_name='productsengine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
