# Generated by Django 4.2.20 on 2026-09-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsengine',
            name='store_id',
        ),
        migrations.AddField(
            model_name='productsengine',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.storeengine'),
        ),
    ]
