# Generated by Django 4.2.20 on 2026-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_brand_shippingmethod_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
