# Generated by Django 4.2.20 on 2026-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_advertisement_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='product_media/'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
